version: '3.3'
services:
  deps:
    image: 'node:10.12'
    volumes:
      - './package.json:/package.json:cached'
      - './yarn.lock:/yarn.lock:cached'
      - 'node_modules:/node_modules:delegated'
    working_dir: '/'
    command: 'yarn install'

  master:
    image: 'citusdata/citus:8.2.1'
    labels:
      - 'com.citusdata.role=Master'
    ports:
      - 5432
    volumes:
      - './db/setup.sql:/docker-entrypoint-initdb.d/setup.sql:cached'

  worker_1: &worker
    image: 'citusdata/citus:8.2.1'
    depends_on:
      - master
    labels:
      - 'com.citusdata.role=Worker'
  worker_2: *worker
  worker_3: *worker

  manager:
    image: 'citusdata/membership-manager:0.2.0'
    depends_on:
      - master
    restart: 'always'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'

  server:
    image: 'node:10.12'
    depends_on:
      - deps
      - master
    environment:
      POSTGRES_USER: 'postgres'
    ports:
      - 5556:5556
    restart: 'always'
    volumes:
      - 'node_modules:/app/node_modules:delegated'
      - './src:/app/src:cached'
      - './package.json:/app/package.json:cached'
    working_dir: '/app'
    command: 'yarn run server'

volumes:
  node_modules:
